name: cross_proto
description: A cross platform RPC demo using protobuf
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  protobuf: ^4.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
