name: cross_proto
description: A cross platform RPC demo using protobuf
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  protobuf: ^4.0.0
  grpc: ^4.0.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
