name: grpc_over_json_rpc
description: A Dart library that bridges gRPC/Protobuf generated services with JSON-RPC, allowing you to reuse Protobuf service definitions in JSON-RPC implementations.
version: 1.0.0
repository: https://github.com/AoEiuV020/flutter_cross_rpc/tree/main/packages/grpc_over_json_rpc

environment:
  sdk: ^3.7.2

dependencies:
  async: any
  grpc: ^4.0.4
  http: ^1.2.0
  json_rpc_2: ^3.0.3
  stream_channel: ^2.1.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  web_socket_channel: any
  cross_proto:
    path: ../cross_proto
