name: server_grpc
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  cross_proto: any
  cross_server: any
  grpc: any

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
