name: cross_server
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  cross_proto:
    path: ../cross_proto
  cross_wrapper:
    path: ../cross_wrapper
  cross_json_rpc:
    path: ../cross_json_rpc
  grpc: any

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  stream_channel: ^2.1.4
