name: cross_json_rpc
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  async: ^2.13.0
  grpc: ^4.0.4
  json_rpc_2: ^3.0.3
  stream_channel: ^2.1.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  web_socket_channel: any
  cross_proto:
    path: ../cross_proto
