name: cross_json_rpc
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  cross_wrapper:
    path: ../cross_wrapper
  json_rpc_2: ^3.0.3
  stream_channel: ^2.1.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
